### ISSUE TITLE
Nagyvak értékének meghatározása

### ISSUE THREAD

**Issue by NPEFactory** [wcs-katedra/poker-autocomplete#3]
Számítsuk ki a nagyvak értékét. A nagyvak értéke a kisvak kétszerese.

**Comment by c3ntipede** [comment]
getActivePlayer() metódust megírva, ami lekérdezi az aktuális játékost, aki játszik.

**Comment by BalazsMartonZoltan** [comment]
calculateBigBlind() done, smallBlind*2. Nem bonyolítottam túl.
