### ISSUE TITLE
A látható lapok kiértékelése

### ISSUE THREAD

**Issue by NPEFactory** [wcs-katedra/poker-autocomplete#6]
A kezünkben és asztalon lévő lapok kiértékelése 
Ismerje fel ha pár, duplapár, drill ... stb van nálunk

**Comment by BalazsMartonZoltan** [comment]
hogy kell magamat hozzárendelni? :D

**Comment by NPEFactory** [comment]
Assign jobb oldalt
ugye van ott olyan h tasak
alatta milestone
és alatta ott van a assign ....

2015-03-17 15:56 GMT+01:00 BalazsMartonZoltan notifications@github.com:
